### ISSUE TITLE
RS32 scale and rings not correct

### ISSUE THREAD

**Issue by james-ward** [RoboSense-LiDAR/ros_rslidar#22]
I have an RS32 lidar. When I use the RSView.exe program I can get good scans.
![2019-06-04-15-27-12-RS-32-Data](https://user-images.githubusercontent.com/1538432/58855654-edfd2800-86e3-11e9-87cc-9c4e307377be.png)

In RViz the scale is wrong (approximately half size) and some of the rings appear at the max range (200m).
![Screenshot from 2019-06-04 15-30-14](https://user-images.githubusercontent.com/1538432/58855820-55b37300-86e4-11e9-8af3-46fd043f72f3.png)

I am using the latest version of the ROS driver on the master branch. The configuration files are the same for RSView.exe and ROS.
My firmware versions are: top - 04 4d 01 00 00, bottom - 03 e9 01 00 00

**Comment by Tony-HIT** [comment]
Have you already fix the problem?
