### ISSUE TITLE
ROS Message per point instead of one revolution

### ISSUE THREAD

**Issue by donrv** [RoboSense-LiDAR/ros_rslidar#30]
Hi,
Is there any setting to output ROS pointcloud2 message per point instead of per revolution?
Currently, my RS16 is set to 600 RPM and getting 10 Messages per second. I want to read messages in realtime instead of accumulating per revolution.

**Comment by HaoQChen** [comment]
> Hi,
> Is there any setting to output ROS pointcloud2 message per point instead of per revolution?
> Currently, my RS16 is set to 600 RPM and getting 10 Messages per second. I want to read messages in realtime instead of accumulating per revolution.

maybe you can change `config_.npackets` in `rslidarDriver::poll` from rsdriver.cpp. This will change the package number of each scan

**Comment by donrv** [comment]
@HaoQChen Thank you, Got it
