### ISSUE TITLE
建了个微信群, 欢迎对激光雷达感知技术感兴趣的小伙伴加入，欢迎多拉人加入

### ISSUE THREAD

**Issue by deepmeng** [RoboSense-LiDAR/ros_rslidar#33]
![image](https://user-images.githubusercontent.com/8176780/83213880-d3924900-a195-11ea-8a69-16a277f52a4e.png)

**Comment by Qin-xs** [comment]
二维码过期了，可以留下群号吗？

**Comment by deepmeng** [comment]
@Qin-xs
