### ISSUE TITLE
Lidar's motor start and stop spinning intermittently

### ISSUE THREAD

**Issue by shrr98** [RoboSense-LiDAR/ros_rslidar#38]
This question is not about the ros package, rather, it is about the sensor's behaviour. I have used the lidar with no issues for several times. Now, suddenly, I tried to use the lidar again, ran the rs_lidar_16.launch and found out that the visualization was quite strange (the data appeared disappeared intermittently). After I checked the lidar, it actually started and stopped spinning intermittently, with a constant interval, i.e about 10 seconds stopping and 1 second spinning. I also have checked the power input to Interface box and there was no problem ( LED was in solid color, and the voltage was 12V). After checking the fault diagnostic (using RSView), I got the data shown here:

![Fault Diagnostic](https://user-images.githubusercontent.com/37062490/76169806-772f1700-61ae-11ea-89fb-19f85b55b98c.png)
 

I am wondering what is wrong with my sensor?

I am asking here because I could not find any forum for RoboSense LiDAR.

**Comment by shrr98** [comment]
I've solved this by contacting the RoboSense and updating the bottom board firmware.

**Comment by BLAZE-GEC** [comment]
> I've solved this by contacting the RoboSense and updating the bottom board firmware.

how did u solve , steps taken by u, or how did u contact robosense
