### ISSUE TITLE
Fixed frame does not exist

### ISSUE THREAD

**Issue by qrort** [RoboSense-LiDAR/ros_rslidar#39]
I have successfully downloaded and built the driver. I am trying to visualise pointcloud from `.pcap `file according to the tutorial. I have edited the `.launch` file and typed in the cmd `roslaunch rslidar_pointcloud rs_lidar_32.launch`. There are no points on rviz grid as there is the error
`No tf data. Actual error: Fixed Frame [rslidar] does not exist`. I am really new to ROS and I am struggling to fix that

**Comment by sergorl** [comment]
@qrort , did you fix it?

**Comment by qrort** [comment]
Unfortunately, no; it is no more relevant though. I could guess it happened because I was launching ROS on a virtual machine, but I had no other choice at the moment.

**Comment by ok-kewei** [comment]
@sergorl , do you have the answer for that ?

**Comment by ok-kewei** [comment]
Under RVIZ > Displays> Global Options > Fixed Frame, key-in 'rslidar'.
