### ISSUE TITLE
Wrong build dependencies

### ISSUE THREAD

**Issue by bochen87** [RoboSense-LiDAR/ros_rslidar#4]
In rslidar_driver, you've got a catkin build dependency on rslidar_input https://github.com/RoboSense-LiDAR/ros_rslidar/blob/df3332b0c77bec58197cafc231b5f735c5276ffc/rslidar_driver/package.xml#L29
This catkin package doesn't exist

When running `rosdep install --from-paths /path/to/ws/src --ignore-src` this creates an error 
```
rslidar_driver: Cannot locate rosdep definition for [rslidar_input] 
```

**Comment by Tony-HIT** [comment]
we can delete this sentence in the package.xml

**Comment by bochen87** [comment]
that would be great! please delete

**Comment by Tony-HIT** [comment]
Please check the latest commit, already delete.

**Comment by bochen87** [comment]
Great, thanks!

**Comment by james-ward** [comment]
This issue was reintroduced in commit:
d93f1d7493b8819b2f158241a2cc05e020bde451

**Comment by facontidavide** [comment]
Indeed https://github.com/RoboSense-LiDAR/ros_rslidar/blob/master/rslidar_driver/package.xml#L29
:(
