### ISSUE TITLE
How to rotate pointcloud in ros_rslidar?Because I want to change  the frame direction of published cloud   

### ISSUE THREAD

**Issue by aidenyao** [RoboSense-LiDAR/ros_rslidar#51]
How to rotate pointcloud in ros_rslidar?

**Comment by HaoQChen** [comment]
You can use our new driver [rs_driver](https://github.com/RoboSense-LiDAR/rs_driver)

We provide a method to do it [how_to_use_transformation_function](https://github.com/RoboSense-LiDAR/rs_driver/blob/main/doc/howto/how_to_use_transformation_function.md)
